### ISSUE TITLE
Not scanning

### ISSUE THREAD

**Issue by pietervw** [shady786/cordova-intermec-scanner#1]
Hi @shady786 

Thanks for your work with this plugin. I'm running it on the Honeywell EDA51 with an Intermec scanner.

The scanner doesn't seem to activate for me. It logs to the console but never activates.
`intermecScanner.js: is created`
`ntermecScanner.js: activateScanner`

Do you have any idea what I can try to resolve this issue?

Thanks

**Comment by shady786** [comment]
Hi @pietervw Please confirm your cordova version ?
